### ISSUE TITLE
Two NuGet Packages, which one is real ?

### ISSUE THREAD

**Issue by SkyEngine-OSP** [IgnaceMaes/MaterialSkin#158]
i've been keeping a copy of the downloaded package for a very long time and just considered checking the NuGet repo recently. The thing is, theres two MaterialSkin NuGet Packages. There used to be only one of them. Which is real and which should i use ? Thanks.

below is a snipped shot of the NuGet Repo

![image](https://cloud.githubusercontent.com/assets/12471935/25061175/fb64220e-21e2-11e7-920c-3a38482262bb.png)

**Comment by IgnaceMaes** [comment]
Interesting, the first one is the only official one managed by me. There isn't even a v0.2.2 out. I'm guessing someone compiled the latest version of the repository and uploaded it to NuGet, but I didn't verify that. 

If you want to use the latest version I suggest compiling the library from GitHub yourself, otherwise use the first NuGet package shown.

**Comment by jeranio** [comment]
Hi,

I dont see the listview control on the 0.2.1 version. How do I get that becuase in your gitgub example you do use it.

**Comment by SomeOneMore** [comment]
The second version is for Framework > 2.6.1
