### ISSUE TITLE
Form Closing Problem

### ISSUE THREAD

**Issue by manusoft** [IgnaceMaes/MaterialSkin#264]
I have two forms in my project  frmContactList and frmContact. When I start the program it will show frmContact then i will click Create button to show frmContact. The problem is when I close frmContact form, it will close all forms. How can I fix this.

**Comment by falcomus** [comment]
Change method "TerminateOnClose" in "MaterialForm.cs"  (~ at Line 651]

Before:

        private void TerminateOnClose(object sender, FormClosedEventArgs e)
        {
            Application.Exit();
        }

After:

        private void TerminateOnClose(object sender, FormClosedEventArgs e)
        {
            if (Application.OpenForms.Count > 0  && this == Application.OpenForms[0])
                Application.Exit();
        }

This will  fix this problem.

**Comment by falcomus** [comment]
or shorter:

//Close application only if only one form is open  (the MainForm

if (Application.OpenForms.Count == 1)
    Application.Exit();

**Comment by jmelendezdev** [comment]
Another native option is:

`if (ActiveMdiChild != null) Application.Exit();`

**Comment by manusoft** [comment]
Thank you all.
@falcomus  
@jmelendezdev

**Comment by benjachiban** [comment]
where do I find that file? 
because when installing through nuget, it only finds *.dll files

**Comment by falcomus** [comment]
Hello,you can download the source code here:https://github.com/IgnaceMaes/MaterialSkinI don't know if there are VisualBasic sources available,if you can't find it - maybe you can convert the C# files with a VB to C# converter.I did a conversion from VB to C#, it worked perfect.I think it should also wirk in the other direction.If you can't find VB sources or can't convert it,please write me again ...Best regardsClaus--Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 23.01.24, 22:43 schrieb benjachiban ***@***.***>:

   
  where do I find that file? because when installing through nuget, it only finds *.dll files

**Comment by falcomus** [comment]
https://marketplace.visualstudio.com/items?itemName=SharpDevelopTeam.CodeConverter

**Comment by falcomus** [comment]
https://marketplace.visualstudio.com/items?itemName=SharpDevelopTeam.CodeConverter
