### ISSUE TITLE
Double tab key for move to next MaterialSingleLineTextField

### ISSUE THREAD

**Issue by carlosvzz** [IgnaceMaes/MaterialSkin#51]
When you have 2 (or more) MaterialSingleLineTextField with consecutive tab order, you need to press Tab twice to get the focus on the next one.... i'm looking to just need 1 press on tab to get the focus on next Textfiled

**Comment by lukeskinner** [comment]
I'll see if I can make a PR for this later today - it only requires 2 lines of code to be added to the ```MaterialSingleLineTextField``` control. 

This is happening because the ```MaterialSingleLineTextField``` component inherits from the ```Control``` base class and adds a ```TextBox``` to its control collection. This means there are technically 2 controls inside the ```MaterialSingleLineTextField```. Setting the TabStop property on the ```MaterialSingleLineTextField``` to false and the baseTextBox to true fixes this.

```c#
public MaterialSingleLineTextField()
{
   //... 
   baseTextBox.TabStop = true;
   this.TabStop = false;
}
```

**Comment by carlosvzz** [comment]
Thanks, that's  the solution .... now it works with just 1 tab press .....

**Comment by Frank-Explorer** [comment]
Why this control need to add a textbox control inside the control, it seems just inherited from the textbox can do the same work.

**Comment by IgnaceMaes** [comment]
@lukeskinner Thanks for posting the solution. I'm currently quite busy with my exams but if I find the time I'll make a commit to fix this issue. (If you haven't done already)

@Frank-Explorer It is needed to be able to draw the bottom line animation. If you want to have your own custom drawing in the TextBox you lose the systems one. (You aren't able to draw a line under it) A workaround for this problem is creating a wrapper control (containing a normal TextBox) and doing the animation in there.

**Comment by P4R4DiSi4C** [comment]
Hello,
You should push this fixes to the nuget package :+1:
