### ISSUE TITLE
Designer shows Controls as Black in Containers

### ISSUE THREAD

**Issue by CallumCarmicheal** [IgnaceMaes/MaterialSkin#52]
Adding controls inside containers like TABCONTROL will make the control(s) black and show up unreadably to the user designing the interface, Although the controls show up inside the application whilst running/debugging.

![Black Controls](http://i.gyazo.com/c932022a409ecb9ac2b9bc3b509db5b0.png)
![RunningControls](http://i.gyazo.com/2410cbbc9709c5b7036295bd50938b57.png)

**Comment by lukeskinner** [comment]
There are two workarounds for this that I've found (you only need to use one not both): 
1. Update each ```TabPage``` in the ```MaterialTabControl``` with ```UseVisualStyleBackColor``` = false
2. Update each ```TabPage``` in the ```MaterialTabControl``` so that the ```BackColor``` property is not set to transparent.

The demo application for MaterialSkin uses the first workaround. 

It seems like this issue only happens in the```System.Windows.Forms.TabPage``` control. This control inherits from ```System.Windows.Forms.Panel``` and then overrides the BackColor property. This overridden property has logic to return the transparent color if ```UseVisualStyleBackColor``` = true and a ```BackColor``` is not manually set.
